version: "1.0"

services:
  api_server:
    build: ./backend/api
    restart: always
    environment:
      - NODE_ENV=production
      - PORT=8001
    ports:
      - 8001:8001
    depends_on:
      - mongo
      - redis
    volumes:
      - type: bind
        source: ./backend/api
        target: /api

  frontend_server:
    build: ./frontend
    restart: always
    environment:
      - PORT=3000
    ports:
      - 3000:3000
    depends_on:
      - api_server
    volumes:
      - type: bind
        source: ./frontend
        target: /frontend

  # checker:
  #   build: ./checker
  #   restart: always
  #   environment:
  #     - PORT=9000
  #   depends_on:
  #     - api_server
  #     - mongo
  #     - redis
  #   volumes:
  #     - type: bind
  #       source: ./checker
  #       target: /checker

  mongo:
    image: mongo:latest
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_ROOT_PASSWORD}
    ports:
      - 27017:27017
    volumes:
      - ./backend/data:/data/db

  redis:
    image: redis:latest
    restart: always
    ports:
      - 6379:6379
